CREATE TABLE "cairn-tool_account" (
	"userId" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "cairn-tool_account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "cairn-tool_bag_type" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cairn-tool_bag_type_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"characterId" integer NOT NULL,
	"bagName" varchar(100) NOT NULL,
	"slotCount" integer DEFAULT 0 NOT NULL,
	"location" varchar(100)
);
--> statement-breakpoint
CREATE TABLE "cairn-tool_character_class" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cairn-tool_character_class_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"characterId" integer NOT NULL,
	"className" varchar(100) NOT NULL,
	"level" integer DEFAULT 1 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cairn-tool_character_stats" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cairn-tool_character_stats_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"characterId" integer NOT NULL,
	"vitMax" integer DEFAULT 0 NOT NULL,
	"vitCurrent" integer DEFAULT 0 NOT NULL,
	"dexMax" integer DEFAULT 0 NOT NULL,
	"dexCurrent" integer DEFAULT 0 NOT NULL,
	"wisMax" integer DEFAULT 0 NOT NULL,
	"wisCurrent" integer DEFAULT 0 NOT NULL,
	"chaMax" integer DEFAULT 0 NOT NULL,
	"chaCurrent" integer DEFAULT 0 NOT NULL,
	"hpMax" integer DEFAULT 0 NOT NULL,
	"hpCurrent" integer DEFAULT 0 NOT NULL,
	"acMax" integer DEFAULT 0 NOT NULL,
	"acCurrent" integer DEFAULT 0 NOT NULL,
	"speed" integer DEFAULT 0 NOT NULL,
	"agility" integer DEFAULT 0 NOT NULL,
	"spellCastingLevel" integer DEFAULT 0 NOT NULL,
	"wisdomProgress" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cairn-tool_character" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cairn-tool_character_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	"portrait" varchar(500),
	"region" varchar(100),
	"status" varchar(100),
	"religion" varchar(100),
	"language" varchar(100),
	"notes" text,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "cairn-tool_coin_purse" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cairn-tool_coin_purse_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"characterId" integer NOT NULL,
	"gold" integer DEFAULT 0 NOT NULL,
	"silver" integer DEFAULT 0 NOT NULL,
	"copper" integer DEFAULT 0 NOT NULL,
	"platinum" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cairn-tool_inventory_slot" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cairn-tool_inventory_slot_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"characterId" integer NOT NULL,
	"slotType" varchar(50) NOT NULL,
	"slotNumber" integer NOT NULL,
	"itemName" varchar(255),
	"itemDescription" text,
	"quantity" integer DEFAULT 1 NOT NULL,
	"isEquipped" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cairn-tool_message" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cairn-tool_message_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"content" varchar(256) NOT NULL,
	"commandResult" jsonb,
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "cairn-tool_potion" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cairn-tool_potion_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"characterId" integer NOT NULL,
	"name" varchar(255) NOT NULL,
	"effect" text,
	"quantity" integer DEFAULT 1 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cairn-tool_scroll" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cairn-tool_scroll_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"characterId" integer NOT NULL,
	"spellName" varchar(255) NOT NULL,
	"level" integer DEFAULT 0 NOT NULL,
	"quantity" integer DEFAULT 1 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cairn-tool_session" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cairn-tool_spell" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cairn-tool_spell_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"characterId" integer NOT NULL,
	"name" varchar(255) NOT NULL,
	"level" integer DEFAULT 0 NOT NULL,
	"school" varchar(100),
	"description" text,
	"isPrepared" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cairn-tool_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"emailVerified" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"image" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "cairn-tool_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "cairn-tool_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
CREATE TABLE "cairn-tool_weapon" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cairn-tool_weapon_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"characterId" integer NOT NULL,
	"name" varchar(100) NOT NULL,
	"damageDie" varchar(20) NOT NULL,
	"proficiency" varchar(50) NOT NULL,
	"traits" text,
	"equipped" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
ALTER TABLE "cairn-tool_account" ADD CONSTRAINT "cairn-tool_account_userId_cairn-tool_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."cairn-tool_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cairn-tool_bag_type" ADD CONSTRAINT "cairn-tool_bag_type_characterId_cairn-tool_character_id_fk" FOREIGN KEY ("characterId") REFERENCES "public"."cairn-tool_character"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cairn-tool_character_class" ADD CONSTRAINT "cairn-tool_character_class_characterId_cairn-tool_character_id_fk" FOREIGN KEY ("characterId") REFERENCES "public"."cairn-tool_character"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cairn-tool_character_stats" ADD CONSTRAINT "cairn-tool_character_stats_characterId_cairn-tool_character_id_fk" FOREIGN KEY ("characterId") REFERENCES "public"."cairn-tool_character"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cairn-tool_character" ADD CONSTRAINT "cairn-tool_character_userId_cairn-tool_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."cairn-tool_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cairn-tool_coin_purse" ADD CONSTRAINT "cairn-tool_coin_purse_characterId_cairn-tool_character_id_fk" FOREIGN KEY ("characterId") REFERENCES "public"."cairn-tool_character"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cairn-tool_inventory_slot" ADD CONSTRAINT "cairn-tool_inventory_slot_characterId_cairn-tool_character_id_fk" FOREIGN KEY ("characterId") REFERENCES "public"."cairn-tool_character"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cairn-tool_message" ADD CONSTRAINT "cairn-tool_message_createdById_cairn-tool_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."cairn-tool_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cairn-tool_potion" ADD CONSTRAINT "cairn-tool_potion_characterId_cairn-tool_character_id_fk" FOREIGN KEY ("characterId") REFERENCES "public"."cairn-tool_character"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cairn-tool_scroll" ADD CONSTRAINT "cairn-tool_scroll_characterId_cairn-tool_character_id_fk" FOREIGN KEY ("characterId") REFERENCES "public"."cairn-tool_character"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cairn-tool_session" ADD CONSTRAINT "cairn-tool_session_userId_cairn-tool_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."cairn-tool_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cairn-tool_spell" ADD CONSTRAINT "cairn-tool_spell_characterId_cairn-tool_character_id_fk" FOREIGN KEY ("characterId") REFERENCES "public"."cairn-tool_character"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cairn-tool_weapon" ADD CONSTRAINT "cairn-tool_weapon_characterId_cairn-tool_character_id_fk" FOREIGN KEY ("characterId") REFERENCES "public"."cairn-tool_character"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "cairn-tool_account" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "cairn-tool_message" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "t_user_id_idx" ON "cairn-tool_session" USING btree ("userId");